# allow inline HTML (slides use it heavily)
MD033: false

# allow long lines
MD013: false

# allow multiple headings with the same content
MD024: false

# allow trailing punctuation in headings
MD026: false

# allow HTML comments for reveal.js directives
MD052: false

# first line doesn't have to be h1 (slides start with HTML/comments)
MD041: false

# don't require alt text on every image (inline logos etc.)
MD045: false

# allow fenced code blocks without language
MD040: false
